version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
  mysql:
    environment:
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: password
    image: library/mysql:5.6.49
    ports:
    - 3306:3306
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
  redis:
    image: library/redis:6.0.8
    ports:
    - 6379:6379